apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-v0.4.1
    heritage: Tiller
    release: adapter
  name: adapter-prometheus-adapter
  namespace: default
data:
  config.yaml: |
    rules:
    - seriesQuery: 'myapp_response_time_sum'
      seriesFilters: []
      resources:
        overrides:
          k8s_namespace:
            resource: namespace
          k8s_pod_name:
            resource: pod
      name:
        matches: "myapp_response_time_sum"
        as: ""
      metricsQuery: 'rate(myapp_response_time_sum[20s]) / rate(myapp_response_time_count[20s])'
    - seriesQuery: 'myapp_client_connected'
      seriesFilters: []
      resources:
        overrides:
          k8s_namespace:
            resource: namespace
          k8s_pod_name:
            resource: pod
      name:
        matches: "myapp_client_connected"
        as: ""
      metricsQuery: <<.Series>>{<<.LabelMatchers>>,container_name!="POD"}
