apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: domain-deployment-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: domain
        version: v1
    spec:
      containers:
      - name: domain
        imagePullPolicy: Never
        image: domain:latest
        env:
        - name: DOMAIN_API_VERSION
          value: v1
