kind: Service
apiVersion: v1
metadata:
  name: "domain-service"
spec:
  selector:
    app: "domain"
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30037
