kind: Service
apiVersion: v1
metadata:
  name: "front-service"
spec:
  selector:
    app: "front"
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30036
