apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: domain-deployment-v2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: domain
        version: v2
    spec:
      containers:
      - name: domain
        imagePullPolicy: Never
        image: domain:latest
        env:
        - name: DOMAIN_API_VERSION
          valueFrom:
            secretKeyRef:
              key: version
              name: mysecret
