apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      containers:
      - name: front
        imagePullPolicy: Never
        image: front:latest
        env:
        - name: DOMAIN_API_URL
          value: http://domain-service:5000
