apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: domain-deployment-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: domain
        version: v2
    spec:
      containers:
      - name: domain
        imagePullPolicy: Never
        image: domain:latest
        env:
        - name: DOMAIN_API_VERSION
          value: v2
---
kind: Service
apiVersion: v1
metadata:
  name: "domain-service"
spec:
  selector:
    app: "domain"
    version: "v2"
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: domain-route
spec:
  hosts:
  - domain-service
  http:
  - route:
    - destination:
        host: domain-service
        subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: domain-destination
spec:
  host: domain-service
  subsets:
  - name: v2
    labels:
      version: v2
---
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      containers:
      - name: front
        imagePullPolicy: Never
        image: front:latest
        env:
        - name: DOMAIN_API_URL
          value: http://domain-service:5000
---
kind: Service
apiVersion: v1
metadata:
  name: "front-service"
spec:
  selector:
    app: "front"
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: front-destination
spec:
  host: front-service
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-route
spec:
  hosts:
  - "*"
  gateways:
  - front-gateway
  http:
  - route:
    - destination:
        host: front-service
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: front-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
