apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-sim
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-sim
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: myapp_response_time_sum
      target:
        type: AverageValue
        averageValue: 10
  - type: Pods
    pods:
      metric:
        name: myapp_client_connected
      target:
        type: AverageValue
        averageValue: 20
